# Use container-based infrastructure
sudo: false

language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
scala:
  - 2.10.6
jdk:
  - oraclejdk8

script:
 - sbt ++$TRAVIS_SCALA_VERSION deploy/scripted