sudo: false
language: scala
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
scala:
- 2.10.6
jdk:
- oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION deploy/scripted
env:
  global:
  - secure: ZRDLCVAMST9jxORY3c9kz5DAgkhoXsQnC3Z7m8XOP0bgx8Rp1xFTWxNB99MpD2CgjP85BbgD+GQAOYIk46dd4BtFXgIOijzyDoTAtBmoCVDU6ddBBl1z2v6S9pnkkeuxmVlhPvBPQ16nZ6+ZP8dGA2nAXV2xql9r80yTYaePj50MTl/tQMAL34zuuxqHF06f0bdCB/DBrhtCdDRp2NSNvLLWBzgVp2LjEZrLVoGHLLkdAknJPt+RuaqXg7RyxLok8vPUwtHQnW4BGZ/zozBGR34yygIRH/nSKIIiP6gqEMnU0H5D2NWmUOTyG7Fvj8Q8kguzq82usr/qjG3y9ZtLqhvMBrE3gpuF/ci41/iE2vDGq05SQzO3Riu6ROvV9nvUSdcBCeD9pbYQrh2rPkK/bCspJ6BHrK91NCf4KLDO7/YjP2yLCpY5tZC61Tzcp/T+FpfBPJxGR1bZbHoKqpp+dlR5AVcxe1gdam0SAE0cuzRAIXdWDAvvUNU9meG0+iD0S0UvNRDVKNRCaWUCAnXv9trNWYW8creoVgBYTHtpecspfWJ5q9UUg7xAq4hfQ7C57E2JkUM3y/CnWkOAtXLRhdZfjkCCtTw0Z6SW1+h+i6GBbuQ8t24BxCzLS0oCG7b6Hd0VdzJgikMzuq5RMl3WX87PLO68RbR0Lz1XrfZSxHc=
  - secure: vQHm4cuDdNyZDYdU8tDCCIag+20AOPDdEithAWaHXpbxS5NoHZtKVKgSM73ZYE7uRapBMMJsOp2DCZfbadg99KtfcwLv8AWTSIGV8K3Z3bKnnEYksi47BIr9c0G0M4ZarFP6QuUuN6NtGs76tBg8Vbz8gCc2DH6y20wbQLzEl9gg+SW9UAWWE4YA03j6S4G/3IShvh8ZAQNdkIuts2npWjCGswDaSc9L6k9qx0PxK8OpEWMnG0zek1EggUfZGeu8Y2n5iw/79oiMSRLNNt3sU79/P8yy6LIh5qnAYsuO1jG7G6LDlCi6tOalDNH4n/zbYgMOrcodhR1TdFS8/zW0HoOJoGkcsrZVNxpwrq6CC7RN0Fqe77NLez2dmAgWldIdf9sPNmbABBIT8cfUEjpF+0v6ng/esLweiBdqjzAX99DbhmprWrFZJ+MmY3VLpY9R1bP2wSgrUc2RFGLo/iGOUu5Kk8SMvlnmJhYUwqo8HqJEzcrnFsczMtvV3CmXbcK+EpZQdJnyoKQ2c+N6FyAyjSNZ+9q1l8N/6eh/s4kHTlzxz1j+PcgtHAgpO62QQGuzKvyMbJRZCPQxuthwKCAcshGQULW1ApbZq7i7Vg6PL1BpKwsG8ob0VJfABWjlSAcL241f10tV3w/eIN11I9qendYafu6Lv9ytdtFYWkzb8Xk=
