# Use container-based infrastructure
sudo: false

language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

jdk:
  - oraclejdk8

script:
 - sbt ++$TRAVIS_SCALA_VERSION deploy/scripted